target-ppc: fix build break for ppc64abi32-linux-user
This patch fixes the following build break when building the
ppc64abi32-linux-user target:

target-ppc/misc_helper.o:(.toc+0x0): undefined reference to `source_is_powerkvm_211'

It is not actually needed since we don't ship ppc64abi32-linux-user, but it is
useful to build all targets during development.

Signed-off-by: Greg Kurz <gkurz@linux.vnet.ibm.com>
Signed-off-by: Alexey Kardashevskiy <aik@ozlabs.ru>